"""Generate static shell completion scripts for the IntentFlow CLI."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from intentflow.cli import build_parser


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "completions"
SHELLS = ("bash", "zsh", "fish")


def _subparsers(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _fish_quote(value: str) -> str:
    return (
        '"'
        + value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
        + '"'
    )


def _fish_desc(action: argparse.Action) -> str:
    if not action.help or action.help == argparse.SUPPRESS:
        return ""
    return f" -d {_fish_quote(action.help)}"


def _fish_parser_desc(parser: argparse.ArgumentParser) -> str:
    if not parser.description:
        return ""
    return f" -d {_fish_quote(parser.description)}"


def _fish_condition(command: str | None = None) -> str:
    if command is None:
        return "__fish_use_subcommand"
    return f"__fish_seen_subcommand_from {command}"


def _fish_option_lines(command: str | None, parser: argparse.ArgumentParser) -> list[str]:
    lines: list[str] = []
    condition = _fish_condition(command)
    for action in parser._actions:
        if not action.option_strings:
            continue
        for option in action.option_strings:
            if option.startswith("--"):
                flag = f" -l {option[2:]}"
            elif option.startswith("-"):
                flag = f" -s {option[1:]}"
            else:
                continue
            args = ""
            if action.choices:
                args = " -xa " + _fish_quote(
                    " ".join(str(choice) for choice in action.choices)
                )
            elif action.nargs != 0 and not isinstance(
                action, (argparse._StoreTrueAction, argparse._StoreFalseAction)
            ):
                args = " -r"
            lines.append(
                f"complete -c intentflow -n {_fish_quote(condition)}{flag}{args}{_fish_desc(action)}"
            )
    return lines


def _fish_completion(parser: argparse.ArgumentParser) -> str:
    subcommands = _subparsers(parser)
    lines = [
        "# fish completion for intentflow",
        "# Generated by scripts/generate_completions.py; do not edit by hand.",
        "complete -c intentflow -f",
    ]
    lines.extend(_fish_option_lines(None, parser))
    for name, subparser in subcommands.items():
        lines.append(
            "complete -c intentflow -n "
            f"{_fish_quote(_fish_condition())} -a {_fish_quote(name)}"
            f"{_fish_parser_desc(subparser)}"
        )
    for name, subparser in subcommands.items():
        lines.extend(_fish_option_lines(name, subparser))
        lines.append(
            "complete -c intentflow -n "
            f"{_fish_quote(_fish_condition(name))} -r -F"
        )
    return "\n".join(lines) + "\n"


def render_completions() -> dict[str, str]:
    try:
        import shtab
    except ImportError as exc:
        raise SystemExit(
            "shtab is required to generate bash/zsh completions; "
            "install the dev extra with: pip install -e '.[dev]'"
        ) from exc

    parser = build_parser()
    return {
        "intentflow.bash": shtab.complete(parser, "bash"),
        "intentflow.zsh": shtab.complete(parser, "zsh"),
        "intentflow.fish": _fish_completion(parser),
    }


def main(argv: list[str] | None = None) -> int:
    args = set(argv if argv is not None else sys.argv[1:])
    check = "--check" in args
    output_dir = DEFAULT_OUTPUT_DIR
    output_dir.mkdir(exist_ok=True)
    failed = False
    for filename, content in render_completions().items():
        path = output_dir / filename
        if check:
            if not path.exists() or path.read_text() != content:
                print(f"{path}: stale or missing", file=sys.stderr)
                failed = True
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
