#compdef intentflow

# AUTOMATICALLY GENERATED by `shtab`


_shtab_intentflow_commands() {
  local _commands=(
    "audit:"
    "compile:"
    "explain:"
    "format:"
    "inspect:"
    "lint:"
    "parse:"
    "replay:"
    "run:"
    "validate:"
  )
  _describe 'intentflow commands' _commands
}

_shtab_intentflow_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "(- : *)--version[show program\'s version number and exit]"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_defaults_added=0

_shtab_intentflow_audit_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":the .iflow source (the contract):"
  ":the result JSON from \'run\' (the witness):"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_audit_defaults_added=0

_shtab_intentflow_compile_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--out[write the plan JSON to this file]:out:"
  ":file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_compile_defaults_added=0

_shtab_intentflow_explain_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[emit the explanation as JSON]"
  ":file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_explain_defaults_added=0

_shtab_intentflow_format_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--check[exit 1 if the file is not already formatted (print nothing to stdout)]"
  "--write[rewrite the file in place]"
  ":file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_format_defaults_added=0

_shtab_intentflow_inspect_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[emit the inspection report as JSON]"
  ":file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_inspect_defaults_added=0

_shtab_intentflow_lint_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--strict[exit 1 on warnings]"
  ":file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_lint_defaults_added=0

_shtab_intentflow_parse_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  ":file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_parse_defaults_added=0

_shtab_intentflow_replay_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[emit the normalized artifact as JSON]"
  ":a trace artifact from \'run --trace-dir\':"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_replay_defaults_added=0

_shtab_intentflow_run_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--simulate[alias for --backend simulate (deterministic mocked cognition)]"
  "--backend[cognition backend (default\: simulate\; \'replay\' needs --cassette)]:backend:(anthropic mock openai simulate replay)"
  "--goal[run a single named goal]:goal:"
  "--pipeline[run a named pipeline instead of standalone goals]:pipeline:"
  "--workspace[directory of real evidence files\; collection goes through the action gate]:workspace:"
  "*--approve[pre-grant human approval for an approval-gated action (repeatable)]:approve:"
  "--approve-interactive[block and prompt on the terminal for each approval-gated action]"
  "--approve-webhook[request approval for gated actions from a synchronous webhook]:approve_webhook:"
  "--judge[run an LLM judge on \'judged\' verification rules (separate tier)]:judge:(simulate openai anthropic)"
  "--cassette[replay recorded model responses from this file (with --backend replay)]:cassette:"
  "--record-cassette[record a real backend\'s model responses to this file for later replay]:record_cassette:"
  "--sign-trace[HMAC-sign the trace chain using the IFLOW_TRACE_KEY env var]"
  "--trace-dir[write a timestamped, self-contained trace artifact per run to this dir]:trace_dir:"
  "--trace-out[write the full result (with trace) to a JSON file]:trace_out:"
  "--json[print the full result as JSON]"
  "--verbose[narrate every phase while running]"
  ":file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_run_defaults_added=0

_shtab_intentflow_validate_options=(
  "(- : *)"{-h,--help}"[show this help message and exit]"
  "--json[emit machine-readable JSON diagnostics]"
  ":file:"
)

# guard to ensure default positional specs are added only once per session
_shtab_intentflow_validate_defaults_added=0


_shtab_intentflow() {
  local context state line curcontext="$curcontext" one_or_more='(*)' remainder='(-)*' default='*::: :->intentflow'

  # Add default positional/remainder specs only if none exist, and only once per session
  if (( ! _shtab_intentflow_defaults_added )); then
    if (( ${_shtab_intentflow_options[(I)${(q)one_or_more}*]} +          ${_shtab_intentflow_options[(I)${(q)remainder}*]} +          ${_shtab_intentflow_options[(I)${(q)default}]} == 0 )); then
      _shtab_intentflow_options+=(': :_shtab_intentflow_commands' '*::: :->intentflow')
    fi
    _shtab_intentflow_defaults_added=1
  fi
  _arguments -C -s $_shtab_intentflow_options

  case $state in
    intentflow)
      words=($line[1] "${words[@]}")
      (( CURRENT += 1 ))
      curcontext="${curcontext%:*:*}:_shtab_intentflow-$line[1]:"
      case $line[1] in
        audit) _arguments -C -s $_shtab_intentflow_audit_options ;;
        compile) _arguments -C -s $_shtab_intentflow_compile_options ;;
        explain) _arguments -C -s $_shtab_intentflow_explain_options ;;
        format) _arguments -C -s $_shtab_intentflow_format_options ;;
        inspect) _arguments -C -s $_shtab_intentflow_inspect_options ;;
        lint) _arguments -C -s $_shtab_intentflow_lint_options ;;
        parse) _arguments -C -s $_shtab_intentflow_parse_options ;;
        replay) _arguments -C -s $_shtab_intentflow_replay_options ;;
        run) _arguments -C -s $_shtab_intentflow_run_options ;;
        validate) _arguments -C -s $_shtab_intentflow_validate_options ;;
      esac
  esac
}



typeset -A opt_args

if [[ $zsh_eval_context[-1] == eval ]]; then
  # eval/source/. command, register function for later
  compdef _shtab_intentflow -N intentflow
else
  # autoload from fpath, call function directly
  _shtab_intentflow "$@"
fi
